Add signing service inspection commands
pulp/pulp-cli pull request #189
Opened 2021-03-29 08:22 UTC by mdellweg

fixes #TBA

2021-03-29 08:22 UTC, mdellweg commented
I want to find a way to make this testable before merging.

2021-04-21 22:52 UTC, ggainey requested changes
Can we detach the import/export changes from this PR? Otherwise, this looks great!

2021-04-21 22:52 UTC, ggainey commented on pulpcore/cli/core/context.py
> +    ENTITY = "pulp exporter"
Is this supposed to be part of this PR?

2021-04-21 22:52 UTC, ggainey commented on pulpcore/cli/core/context.py
> +    ENTITY = "pulp export"
Same question here

2021-04-21 22:52 UTC, ggainey commented on pulpcore/cli/core/context.py
> +    ENTITY = "pulp importer"
...and here :)

2021-04-21 22:52 UTC, ggainey commented on tests/assets/setup_signing_service.py
> +    )
:+1:

2021-04-21 22:52 UTC, ggainey commented on tests/assets/sign_deb_release.sh
> +     "}"
:+1:

2021-04-22 08:57 UTC, mdellweg commented on pulpcore/cli/core/context.py
> +    ENTITY = "pulp importer"
sure

2021-04-28 13:49 UTC, ggainey approved these changes
Looks good!

2021-04-28 14:10 UTC, merged