Add a timeout parameter and report timeouts
pulp/pulp-cli pull request #258
Opened 2021-05-31 08:07 UTC by mdellweg

fixes #249

2021-06-09 18:19 UTC, ggainey requested changes

2021-06-09 18:19 UTC, ggainey commented on pulpcore/cli/common/config.py
> +        help=_("Time to wait for backgroud tasks, set to 0 to wait infinitely"),
background

2021-06-10 19:10 UTC, ggainey commented
Post-mypy-pin PR, this still fails lint, and I'm not sure why :(

2021-06-11 10:59 UTC, mdellweg commented
> Post-mypy-pin PR, this still fails lint, and I'm not sure why :(

I believe gh runs those against the branch tips and not trial merges, so it needs rebasing.

2021-06-18 10:11 UTC, mdellweg commented
@ggainey ping

2021-06-18 12:24 UTC, ggainey approved these changes

2021-06-18 12:24 UTC, merged