Validate parameters
pulp/pulp-cli pull request #555
Opened 2022-09-24 14:20 UTC by mdellweg

2022-09-28 15:06 UTC, mdellweg commented
I may be missing some `--*-in` options that are not exercised in tests. So please have a close look if you will.

2022-09-30 15:14 UTC, ggainey requested changes
A couple suggestions, but overall looking good. I'd like to see more tests, esp for rpm-content, but that should be its own issue I think.

2022-09-30 16:24 UTC, mdellweg commented on tests/scripts/pulp_rpm/test_content.sh
> +expect_succ pulp rpm content list --name-in "${RPM_NAME}" --name-in "${RPM2_NAME}"
I have two already...

2022-09-30 16:26 UTC, mdellweg commented on pulpcore/cli/common/generic.py
> +        if "ordering" in kwargs:
No, even when the user does not specify ordering, we will receive `[]` from click. And that fails validation on GroupSomething and SigningServices.

2022-09-30 16:27 UTC, mdellweg commented on pulpcore/cli/rpm/content.py
> +    pulp_option("--pkgId", allowed_with_contexts=(PulpRpmPackageContext,)),
:-D

2022-09-30 16:50 UTC, mdellweg commented on pulpcore/cli/rpm/content.py
> +    pulp_option("--id-in", "id__in", allowed_with_contexts=(PulpRpmAdvisoryContext,)),
I see now! I accidentally added the multiple to "--id" instead.

2022-10-04 13:57 UTC, ggainey approved these changes

2022-10-04 13:57 UTC, ggainey commented on tests/scripts/pulp_rpm/test_content.sh
> +expect_succ pulp rpm content list --name-in "${RPM_NAME}" --name-in "${RPM2_NAME}"
Yeah I have no idea what I was thinking there

2022-10-04 13:57 UTC, merged