Use version specifiers in PluginRequirement
pulp/pulp-cli pull request #679
Opened 2023-04-15 07:38 UTC by mdellweg

Review Checklist:
- [ ] An issue is properly linked. [feature and bugfix only]
- [ ] Tests are present or not feasible.
- [ ] Commits are split in a logical way (not historically).

2023-04-15 07:39 UTC, mdellweg commented
When you realize, you reinvented the wheel...

2023-04-15 08:20 UTC, mdellweg commented
`sed -i -E -e 's/PluginRequirement\("(.*)", (min=)?"([0-9.]*(dev)?)"(, inverted=True)?(, feature=.*)?\)/PluginRequirement("\1", specifier=">=\3"\5\6)/' pulpcore/cli/*/*.py pulp-glue/pulp_glue/*/*.py docs/*`
`sed -i -E -e 's/PluginRequirement\("(.*)", max="([0-9.]*(dev)?)"(, inverted=True)?(, feature=.*)?\)/PluginRequirement("\1", specifier="<\2"\4\5)/' pulpcore/cli/*/*.py pulp-glue/pulp_glue/*/*.py docs/*`

2023-04-18 18:42 UTC, ggainey requested changes

2023-04-18 18:42 UTC, ggainey commented on pulp-glue/pulp_glue/core/context.py
> +    NEEDS_PLUGINS = [PluginRequirement("core", specifier=">=3.23.0")]
:+1:

2023-04-18 18:42 UTC, ggainey commented on pulpcore/cli/core/group.py
> +    "needs_plugins": (PluginRequirement("core", specifier=">=3.23"),),
:+1:

2023-04-18 18:42 UTC, ggainey commented on pulpcore/cli/ansible/repository.py
> +            PluginRequirement("ansible", min="0.15.0", feature="gpgkeys on ansible repositories")
```suggestion
            PluginRequirement("ansible", specifier=">=0.15.0", feature="gpgkeys on ansible repositories")
```

2023-04-19 06:00 UTC, mdellweg commented on pulpcore/cli/ansible/repository.py
> +            PluginRequirement("ansible", min="0.15.0", feature="gpgkeys on ansible repositories")
programmers blind spot...

2023-04-19 12:11 UTC, ggainey approved these changes

2023-04-19 12:11 UTC, merged