WIP Split architecture doc
pulp/pulp-cli pull request #937
Opened 2024-04-02 15:51 UTC by mdellweg

Review Checklist:
- [ ] An issue is properly linked. [feature and bugfix only]
- [ ] Tests are present or not feasible.
- [ ] Commits are split in a logical way (not historically).

2024-04-03 12:43 UTC, pedro-psb requested changes

2024-04-03 12:43 UTC, pedro-psb commented on staging_docs/dev/learn/architecture.md
Internal links are missing a `docs` node: `site:pulp-glue/docs/learn/...`.

2024-04-03 14:06 UTC, mdellweg commented on staging_docs/dev/learn/architecture.md
Can you help me create a docs test building workflow?

2024-04-04 09:55 UTC, mdellweg commented on staging_docs/dev/learn/architecture.md
More strict would definitely be helpful.
If I understand correctly, pulp-docs will always (on each subprojects PRs) build the whole docs site, right? We should be as strict as possible in order not to break the global docs building constantly.

2024-04-04 13:21 UTC, pedro-psb commented on staging_docs/dev/learn/architecture.md
Yes it builds the whole doc everytime.

But the effect on CI stability is quite the opposite, IMO:
If we are strict about broken links, for example, and some repository merges a change with broken links (somehow bypassing PR checks), then every build will fail because of that, whereas a less strict policy on broken links wouldn't prevent building.

2024-04-04 14:06 UTC, mdellweg commented on staging_docs/dev/learn/architecture.md
OK, that's why we need to be at least as strict in PR review.
(bypassing such a check can be considered deliberately evil behaviour)

2024-04-15 12:10 UTC, ggainey approved these changes

2024-04-15 12:10 UTC, merged